title: Shengyao Lu
logo: /assets/img/logo.png
description: "Shengyao Lu (陆晟瑶) is currently a PhD candidate at the University of Alberta, advised by Prof. Di Niu."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
